### PR TITLE
Update export_multispecies.jl

### PR DESCRIPTION
**Pull request by casv2**
Shockingly embarrassing bug, only showed up at species > 3. Not sure how this ended up (still being) here...

### CODE REVIEW

**Comment by casv2** [comment]
Actually let's leave this for a minute, something else seems wrong. I've tested this export with 2/3 species and Will has confirmed it worked for his 3 species ACE1 models but there seems to be a bug for species > 3... Weird, I'll dig into this, we'll probably need another commit before merging. 

Come to think of it I think, Will would also like to see element-pair specific radial transforms to work with this export, which the Drautz PACE evaluator does allow for. It's just that this export was written before the MultiTransform business, so I guess it's time to also update this export to also eat and export MultiSpecies / MultiTransform LAMMPs potentials.

**Comment by cortner** [comment]
let's not put different issues into a single PR please. Let's focus THIS PR on just the Bugfix. Any news on that?

**Comment by cortner** [comment]
@casv2 -- as agreed on slack, we move all export functionality elsewhere. Since you asked me to hold off on this, I'm not sure what to do here. Should I merge and then delete from the repo, or better to just close the PR without merging?

**Comment by cortner** [comment]
ok, since will has all this in his fork I will just close this now.

**Pull request closed without merging**
