### PR TITLE
Spline export

### PR DESCRIPTION
**Pull request by WillBaldwin0**
some tidying of the export, adding spline export of the pair potential, and changing ACE1 to ACE in `radbasename`.

### CODE REVIEW

**Comment by WillBaldwin0** [comment]
I've made a little update to the ACE1 docs to better explain the export - and to discuss a problem that I've found calling lammps pace from python.

**Comment by WillBaldwin0** [comment]
I've just incorporated the bug fix from #20

**Comment by WillBaldwin0** [comment]
For me personally I probably wouldn't use the ACE1_backup, since I have my own fork with that kind of stuff in.

**Comment by cortner** [comment]
Btw - do you have any evidence about performance or numerical stability. polynomials vs splines?

**Comment by cortner** [comment]
ok - we can discuss whether this is really an issue. If it is then we can implement the radial * envelope in PACE.

**Comment by WillBaldwin0** [comment]
So does the licensing mean that my code for doing the data driven orthogonalisation and such cannot be merged into ACE1?

**Comment by cortner** [comment]
It still isn't clear to me that it really should be in ACE1 to begin with. If my understanding is right then simply need to pass different weights to initialize the polynomial basis. I consider that a "user choice". The core functionality regarding orthogonal polynomials with arbitrary weights has always been in ACE1

**Comment by cortner** [comment]
I assume that eventually ACE1.jl will end up being co-owned by multiple parties and then this will determine how new ideas will get merged into it. Note also that ACE.jl is infinitely more complicated in this regard so whatever happens we need to resolve this issue.

**Pull request closed without merging**
