### PR TITLE
WIP: Committees for Pair potentials + Combined Potentials

### PR DESCRIPTION
**Pull request by cortner**
CC @casv2 @MatthiasSachs

### CODE REVIEW

**Comment by cortner** [comment]
@casv2 - please read the test `test/test_commitee_pair.jl` especially the final sections to make sure you are happy with the level of testing and the defined behaviour: 
```julia

at = rattle!(bulk(:W, cubic=true) * 2, 0.2)

@info("check energy")
E1 = energy(V_comb, at)
E2, co_E = ACE1.co_energy(co_V_comb, at)
println_slim(@test E1 ≈ E2 ≈ mean(co_E))
println_slim(@test co_E ≈ ACE1.co_energy(co_V, at)[2] + ACE1.co_energy(co_Vace, at)[2])

@info("check forces")
F1 = forces(V_comb, at)
F2, co_F = ACE1.co_forces(co_V_comb, at)
println_slim(@test (F1 ≈ F2 ≈ mean(co_F)))
println_slim(@test co_F ≈ ACE1.co_forces(co_V, at)[2] + ACE1.co_forces(co_Vace, at)[2])

@info("check virial")
vir1 = virial(V_comb, at)
vir2, co_vir = ACE1.co_virial(co_V_comb, at)
println_slim(@test (vir1 ≈ vir2 ≈ mean(co_vir)))
println_slim(@test co_vir ≈ ACE1.co_virial(co_V, at)[2] + ACE1.co_virial(co_Vace, at)[2])
```

**Comment by cortner** [comment]
there are additional tests in the rest of the script.

**Comment by cortner** [comment]
From my end this is ready to merge as soon as you confirm (@casv2 )

**Comment by casv2** [comment]
I'm happy for this to be merged

**Pull request merged**
